### PR TITLE
rename

### PR DESCRIPTION
**Pull request by jburel**
Change repo name in readme

### CODE REVIEW

**Comment by atarkowska** [comment]
Looks good https://github.com/snoopycrimecop/omero-webtest/blob/e8bbc1658484aa7983ffda20d2b9bd8ee400247c/README.rst, good to merge

**Comment by jburel** [comment]
@aleksandra-tarkowska:
noticed on https://pypi.python.org/pypi/omero-webtest/0.1.1
that we have a broken link i.e. https://travis-ci.org/openmicroscopy/webtest

and 
``
Home Page: https://github.com/openmicroscopy/webtest
Download URL: https://github.com/openmicroscopy/webtest/tarball/0.1.1
``
@joshmoore: Do we have an organisation account on pypi so I can update it?

**Comment by jburel** [comment]
This is outside the scope of this PR so this can be merged

**Comment by jburel** [comment]
I need to update setup.py too

**Comment by sbesson** [comment]
Briefly discussed with @jburel, `setup.py` needs to be updated to reflect the new repo name. If this is the only change, we could also bump `VERSION` to 0.2.1 and tag/upload to Pypi.

**Comment by jburel** [comment]
0.2.0: is the start of the rename version it was bumped in https://github.com/openmicroscopy/omero-webtest/pull/15

**Review by sbesson — APPROVED** [review]

**Comment by sbesson** [comment]
Ah I didn't realize we never tagged it. 👍 for 0.2.0

**Comment by jburel** [comment]
https://trello.com/c/cyoBblgp/200-renaming-of-web-app updated too

**Comment by jburel** [comment]
removed comment, everything has been sorted now

**Pull request merged**
