### PR TITLE
more examples

### PR DESCRIPTION
**Pull request by atarkowska**
Here we can put more examples from Luca

Examples works against testing server.

URLs:
- https://trout/merge/webtest/examples/23002/embed_rois_selection.html

**IMAGE_ID** should be obtained from https://trout/merge/gallery as there are some public images.

New templates can be added to `templates/webtest/examples`

Rendered template can be saved locally for further testing as a absolute uri is included.

Accompanied with https://github.com/openmicroscopy/management_tools/pull/30

### CODE REVIEW

**Comment by sbesson** [comment]
@aleksandra-tarkowska does that mean we want to deploy gallery on our CI servers?

**Comment by atarkowska** [comment]
@sbesson I think we should. We need to fix bugs there anyway

**Comment by sbesson** [comment]
Replaced by https://github.com/openmicroscopy/webtest/pull/6

**Comment by sbesson** [comment]
What's the status of this PR?

**Comment by will-moore** [comment]
Sorry - I must have missed this and went ahead with #6 which is identical I think.

**Comment by sbesson** [comment]
@will-moore: that's what I also thought originally but this is `embed_rois_selection` while #6 is `embed_external_rois`

**Comment by atarkowska** [comment]
I didn't have time to look what exactly ROI_ID is. I am happy with #6. I will ask Luca to make this example dynamic. Although this shouldn't stop from removing templates from the main line.

**Comment by will-moore** [comment]
Ah, OK. This is actually a different example file from #6 but it is functionality for filtering ROIs in the UI which has been added to the webclient viewer UI itself.
So, this example is not required as a test for the activate_roi(id) method, although I guess it could still be useful. But, I think the ROI IDs do need to be hard-coded according to existing ROIs, so it's not ready to test live in it's current form.

**Comment by atarkowska** [comment]
#15 takes priority

**Pull request closed without merging**
