### PR TITLE
make sure app is in pypi package

### PR DESCRIPTION
**Pull request by atarkowska**
This PR fixes missed app in https://github.com/openmicroscopy/webtest/pull/12

### CODE REVIEW

**Comment by joshmoore** [comment]
:+1: Guess the only question is if we want `git mv webtest omero_webtest` now. If not, I'll go ahead and release this as 0.1.1.

**Comment by atarkowska** [comment]
I think mv would require src changes. Imports won't work

**Comment by atarkowska** [comment]
Go ahead for 0.1.1 please

**Comment by joshmoore** [comment]
Uploaded.

**Pull request merged**
