### PR TITLE
Correct rst

### PR DESCRIPTION
**Pull request by joshmoore**
rst errors were not found until release: See https://github.com/openmicroscopy/webtest/pull/12#issuecomment-245846456

### CODE REVIEW

**Comment by sbesson** [comment]
If rst-lint works as expected :+1: for activating it across the board. The alternate solution I had used in `omego` was a simple unit test https://github.com/ome/omego/blob/master/test/unit/test_readme.py

**Comment by joshmoore** [comment]
https://travis-ci.org/openmicroscopy/webtest/builds/158670595 failed. Fixing now.

**Comment by joshmoore** [comment]
Assuming we have a base omero plugin class for versioning, I could imagine:

```
`./omero-plugin travis`
```

to simplify much of this.

**Comment by joshmoore** [comment]
Green.

**Pull request merged**
