### PR TITLE
Histogram testing

### PR DESCRIPTION
**Pull request by will-moore**
Assessing techniques and performance of histograms - single plane & channel at a time.

Have used Backbone.js for a model to coordinate UI components and React.js as an example of combining these libraries.

Histogram PR for webclient is https://github.com/openmicroscopy/openmicroscopy/pull/4703 and uses histogram code from here.

To test, go to `/webtest/histogram_viewer/:imageId` and  check that the various controls are working (image updates on channel toggle, channel slider, z-change and so does histogram (not for channel toggle).

screen shot 2016-05-26 at 16 24 17

### CODE REVIEW

**Comment by will-moore** [comment]
cc @waxenegger @jburel Following our discussion today, I added a React.js component for Channel Buttons (checkboxes), which updates the Backbone.js model on changes.

**Comment by waxenegger** [comment]
I really like the histograms, d3 is a pretty neat library. 

And, yes, backbone js can be used with react js, it's a bit outside the box since the setState of react usually affects the rendering of the virtual dom as opposed to calling it directly (and it has batching logic in it to combine updates) but it's a perfectly good solution, and, personally, I'm not at all averse to using it.

There needs to be one gap-filler, however, for components like the ol3 viewer which are not part of the model and update/changes would require that one kept references to the component and made actual hard-coded calls on the implementation which is not a situation that one would want. Switching such components flexibly would become a nightmare.

Most recently I tried redux and it works though in essence it is nothing more than a very simple event dispatcher with the side effect that it can keep track of state. Maybe it could be used in the cases where a model update is not an option.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTEST-merge/label=cowfish#313](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=cowfish/313/). See the [console output](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=cowfish/313/consoleText) for more details.
Possible conflicts:
- PR #8 will-moore 'Various fixes for channel overlay viewer'
  - views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTEST-merge/label=trout#313](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=trout/313/). See the [console output](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=trout/313/consoleText) for more details.
Possible conflicts:
  - PR #8 will-moore 'Various fixes for channel overlay viewer'
    - views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTEST-merge/label=seabass#313](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=seabass/313/). See the [console output](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=seabass/313/consoleText) for more details.
Possible conflicts:
  - PR #8 will-moore 'Various fixes for channel overlay viewer'
    - views.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTEST-merge/label=octopus#313](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=octopus/313/). See the [console output](https://ci.openmicroscopy.org/job/WEBTEST-merge/label=octopus/313/consoleText) for more details.
Possible conflicts:
  - PR #8 will-moore 'Various fixes for channel overlay viewer'
    - views.py

**Comment by jburel** [comment]
checking ./views.py
./views.py:491:38: E711 comparison to None should be 'if cond is not None:'
directory ./static

**Comment by will-moore** [comment]
@jburel See comment at https://github.com/openmicroscopy/webtest/pull/8#issuecomment-224548018
If I fix the travis failure, I will get a merge conflict.

**Comment by atarkowska** [comment]
This PR is conflicting with main line anyway, closing as #15 takes priority

**Pull request closed without merging**
