### PR TITLE
adding embedding examples to webtest

### PR DESCRIPTION
**Pull request by atarkowska**
Examples works against testing server.

URLs:
- https://trout/merge/webtest/examples/23006/embed_big_image.html
- https://trout/merge/webtest/examples/23002/embed_viewer.html

**IMAGE_ID** should be obtained from https://trout/merge/gallery as there are some public images.

New templates can be added to `templates/webtest/examples`

Rendered template can be saved locally for further testing as a absolute uri is included.

Accompanied with https://github.com/openmicroscopy/management_tools/pull/30

### CODE REVIEW

**Comment by will-moore** [comment]
https://trout.openmicroscopy.org/merge/webtest/examples/9245/embed_viewer.html (user-3) viewer works but ROIs are not shown and console has error, seems to come from the min.js concatenation?

```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function
```

**Comment by will-moore** [comment]
Same error with https://trout.openmicroscopy.org/merge/webtest/examples/22676/embed_big_image.html (and viewer is not working here).

**Comment by atarkowska** [comment]
@will-moore I removed that 3rd template as is not clear how to modify it. I will come back to it when open a PR with Luca's latest changes

**Comment by will-moore** [comment]
Sorry - that first image doesn't have any ROIs - they are displayed OK at https://trout.openmicroscopy.org/merge/webtest/examples/9227/embed_viewer.html
The big image viewer is working on some images and not others (above link to image 22676 doens't work but https://trout.openmicroscopy.org/merge/webtest/examples/21547/embed_big_image.html is fine).
As discussed, just need to add latest example: https://github.com/lucalianas/openmicroscopy/blob/third_party_rois/examples/Web/embed_external_rois.html

**Pull request merged**
